# Generated by Django 3.2.5 on 2021-08-23 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0002_auto_20210823_1122'),
    ]

    operations = [
        migrations.DeleteModel(
            name='URLForm',
        ),
    ]
