# Generated by Django 3.2.5 on 2021-08-23 13:11

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0003_delete_urlform'),
    ]

    operations = [
        migrations.AddField(
            model_name='inputform',
            name='date',
            field=models.CharField(default=datetime.datetime(2021, 8, 23, 13, 11, 5, 877100, tzinfo=utc), max_length=100, unique=True),
        ),
        migrations.AddField(
            model_name='inputform',
            name='url',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
