# Generated by Django 3.2.5 on 2021-08-23 13:13

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0004_auto_20210823_1311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inputform',
            name='date',
            field=models.CharField(default=datetime.datetime(2021, 8, 23, 13, 13, 29, 497086, tzinfo=utc), max_length=100, unique=True),
        ),
    ]
