# Generated by Django 3.2.5 on 2021-08-23 13:14

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0005_alter_inputform_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='inputform',
            name='emails',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='inputform',
            name='message',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='inputform',
            name='date',
            field=models.CharField(default=datetime.datetime(2021, 8, 23, 13, 14, 41, 370361, tzinfo=utc), max_length=100, unique=True),
        ),
    ]
