# Generated by Django 3.2.5 on 2021-08-23 14:29

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0006_auto_20210823_1314'),
    ]

    operations = [
        migrations.AddField(
            model_name='inputform',
            name='index',
            field=models.CharField(max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name='inputform',
            name='date',
            field=models.CharField(default=datetime.datetime(2021, 8, 23, 14, 29, 3, 916964, tzinfo=utc), max_length=100, unique=True),
        ),
    ]
