# Generated by Django 3.2.5 on 2021-08-23 15:30

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0007_auto_20210823_1429'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inputform',
            name='index',
        ),
        migrations.AlterField(
            model_name='inputform',
            name='date',
            field=models.CharField(default=datetime.datetime(2021, 8, 23, 15, 30, 12, 183875, tzinfo=utc), max_length=100, unique=True),
        ),
    ]
