# Generated by Django 3.2.5 on 2021-08-23 15:32

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0008_auto_20210823_1530'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=100, null=True)),
                ('date', models.CharField(default=datetime.datetime(2021, 8, 23, 15, 32, 10, 302844, tzinfo=utc), max_length=100, unique=True)),
                ('emails', models.CharField(max_length=100, null=True)),
                ('message', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='InputForm',
        ),
    ]
