# Generated by Django 3.2.5 on 2021-08-24 10:56

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0010_auto_20210823_1533'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportform',
            name='hashKey',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='reportform',
            name='date',
            field=models.CharField(default=datetime.datetime(2021, 8, 24, 10, 56, 21, 805816, tzinfo=utc), max_length=100, unique=True),
        ),
    ]
