# Generated by Django 3.2.5 on 2021-08-24 11:05

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0011_auto_20210824_1056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportform',
            name='date',
            field=models.CharField(default=datetime.datetime(2021, 8, 24, 11, 5, 35, 852103, tzinfo=utc), max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='reportform',
            name='hashKey',
            field=models.CharField(max_length=100000, null=True),
        ),
    ]
