# Generated by Django 3.2.5 on 2021-08-24 15:11

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0012_auto_20210824_1105'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reportform',
            name='index',
        ),
        migrations.AlterField(
            model_name='reportform',
            name='date',
            field=models.CharField(default=datetime.datetime(2021, 8, 24, 15, 11, 33, 316014, tzinfo=utc), max_length=100, unique=True),
        ),
    ]
