# Generated by Django 3.2.5 on 2021-08-25 14:49

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0013_auto_20210824_1511'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportform',
            name='topUrls',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='reportform',
            name='date',
            field=models.CharField(default=datetime.datetime(2021, 8, 25, 14, 49, 6, 695214, tzinfo=utc), max_length=100, unique=True),
        ),
    ]
