# Generated by Django 3.2.5 on 2021-09-03 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0014_auto_20210825_1449'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reportform',
            name='date',
        ),
        migrations.AddField(
            model_name='reportform',
            name='scanID',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
    ]
